### ISSUE TITLE
Allow importing from JavaScript files

### ISSUE THREAD

**Issue by rayshan** [Updater/node-sass-json-importer#18]
Hello,

It'll be nice if we can import from JavaScript files, this way we can share calculated values. We can do the calculation in Sass and JavaScript but then we're duplicating logic. For example:

```js
const THUMBNAIL_SCALE_NARROW = 100,
    GOLDEN_RATIO = 1.62,
    COLUMN_WIDTH_NARROW = Math.floor(GOLDEN_RATIO * THUMBNAIL_SCALE_NARROW);

module.exports = {
    THUMBNAIL_SCALE_NARROW: THUMBNAIL_SCALE_NARROW,
    GOLDEN_RATIO: GOLDEN_RATIO,
    COLUMN_WIDTH_NARROW: COLUMN_WIDTH_NARROW
};
```

**Comment by pmowrer** [comment]
Hi @rayshan! Sounds like a good idea, but this repository is specifically about importing JSON. Not sure if there's another importer out there that imports JavaScript (or more specifically, CommonJS in your case).

**Comment by MattKunze** [comment]
FWIW it's pretty trivial to support JS files as well since it's just using node's require mechanism:

https://github.com/MattKunze/node-sass-json-importer/pull/1/files

This only handles modules that export a top level POJO, but for me the big win is avoiding the uneccessarily restrictive syntax of JSON (allow comments, simpler quoting rules, etc). It would also let you dynamically generate content if you wanted I guess, though that's not my aim
